version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prod.db
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-default-key-change-in-production}
      - SKIP_ENV_VALIDATION=1
    volumes:
      - ./data/database/prod.db:/app/prisma/prod.db
      - ./data/uploads:/app/public/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/var/www/uploads:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - app
    restart: unless-stopped

volumes:
  app_db:
  nginx_cache:
